# ??? ??? ??? ??
spring.security.user.name=user
# ??? ??? ???? ??
spring.security.user.password=1234
# ?? ?? ?? ?? ?? ?? (?? ?? ??)
server.servlet.session.cookie.same-site=strict
# ?????? ?? ?? (PostgreSQL?)
spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
# ?????? ?? ???
spring.datasource.username=postgres
# ?????? ?? ????
spring.datasource.password=1234
# DB ??? ?? ?? ??
spring.jpa.hibernate.ddl-auto=update
# ??? SQL ?? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true